# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Gems


plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Setup
title:            Kezhi Li
tagline:          'Personal Site'
description:      'Personal site for Kezhi Li.'
url:              "http://little-black-sjtu.github.io/likezhi.github.io"
baseurl:          "/"

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
paginate_path: "page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
