# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Gems


plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Setup
title:            Kezhi Li
tagline:          'Personal Site'
description:      'Personal site for Kezhi Li. A self-driven, quick starter, passionate researcher who enjoys solving challenging real-world problems.'
url:              "http://little-black-sjtu.github.io/likezhi.github.io"
baseurl:          ""